name: commit-solution-components

on:
  workflow_dispatch:

jobs:
  build:
    #runs-on: [self-hosted, windows, x64]
    runs-on: windows-latest
    env:
      environmentUrl: https://dreamingincrm.crm6.dynamics.com
      userName: "actionsuser@dreamingincrm.onmicrosoft.com"
      applicationId: "e605bea5-f749-4f51-8508-8c6891d9f8dc"
      solution: "GitHubActionsDemo"
      timeZone: "AUS Eastern Standard Time"
      PacCli.PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - id: who-am-i
        name: Connecting to ${{ env.environmentUrl }} as ${{ env.userName }}
        uses: microsoft/powerplatform-actions/who-am-i@v0.1.8
        with:
          environment-url: ${{ env.environmentUrl }}
          user-name: ${{ env.userName }}
          password-secret: ${{ secrets.password }}
        
      - id: increment-solution-version
        name: Bump ${{ env.solution }} version to ${{ github.run_number }}
        uses: microsoft/powerplatform-actions/update-solution-version@b24403b
        with:
          patch-version: "${{ github.run_number }}"
          
      - id: solution-version
        name: Getting version information for ${{ env.solution }}
        uses: mavrosxristoforos/get-xml-info@1.0
        with:
          xml-file: "Solutions/${{ env.solution }}/src/Other/Solution.xml"
          xpath: "//ImportExportXml/SolutionManifest/Version"
          
      - id: export-managed-solution
        name: Export ${{ env.solution }} as Managed
        uses: microsoft/powerplatform-actions/export-solution@v0.1.8
        with:
          environment-url: ${{ env.environmentUrl }}
          user-name: ${{ env.userName }}
          password-secret: ${{ secrets.password }}
          solution-name: ${{ env.solution }}
          solution-output-file: "${{ env.solution }}_managed.zip"
          working-directory: "out"
          managed: true

      - id: export-unmanaged-solution
        name: Export ${{ env.solution }} as Unmanaged
        uses: microsoft/powerplatform-actions/export-solution@v0.1.8
        with:
          environment-url: ${{ env.environmentUrl }}
          user-name: ${{ env.userName }}
          password-secret: ${{ secrets.password }}
          solution-name: ${{ env.solution }}
          solution-output-file: "${{ env.solution }}.zip"
          working-directory: "out"

      - id: unpack-solution
        name: Unpack ${{ env.solution }}
        uses: microsoft/powerplatform-actions/unpack-solution@v0.1.8
        with:
          solution-file: "out/${{ env.solution }}.zip"
          solution-folder: "Solutions/${{ env.solution }}/src"
          solution-type: "Both"
          overwrite-files: true

      - id: branch-name
        name: Set Branch Name variable
        run: |
          echo "::set-output name=branchName::${{ env.solution }}_${{ steps.solution-version.outputs.info }}"

      - id: create-solution-branch
        name: Create ${{ steps.branch-name.outputs.branchName }} branch
        uses: microsoft/powerplatform-actions/branch-solution@v0.1.8
        with:
          solution-folder: "Solutions/${{ env.solution }}"
          solution-target-folder: "Solutions/${{ env.solution }}"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          branch-name: ${{ steps.branch-name.outputs.branchName }}

      - uses: octokit/request-action@v2.x
        name: Create PR for branch ${{ steps.branch-name.outputs.branchName }}
        id: create_pr
        with:
          owner: "rajyraman"
          repo: ${{ github.repository }}
          route: POST /repos/:repo/pulls
          title: ${{ steps.branch-name.outputs.branchName }}
          head: ${{ steps.branch-name.outputs.branchName }}
          base: "main"
          maintainer_can_modify: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
