# Workflow to initialise the solution in GitHub from an existing solution in CDS
name: initialise-repo

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    env:
      url: https://dreamingincrm.crm6.dynamics.com
      username: "actionsuser@dreamingincrm.onmicrosoft.com"
      solution: "GitHubActionsDemo"
    steps:
      - uses: actions/checkout@v2

      - id: who-am-i
        uses: microsoft/powerplatform-actions/who-am-i@v0.1.8
        with:
          environment-url: ${{ env.url }}
          user-name: ${{ env.username }}
          password-secret: ${{ secrets.password }}

      - id: clone-solution
        uses: microsoft/powerplatform-actions/clone-solution@v0.1.8
        with:
          environment-url: ${{ env.url }}
          user-name: ${{ env.username }}
          password-secret: ${{ secrets.password }}
          solution-name: ${{ env.solution }}
          target-folder: "./Solutions"

      - id: solution-version
        uses: mavrosxristoforos/get-xml-info@1.0
        with:
          xml-file: "Solutions/${{ env.solution }}/src/Other/Solution.xml"
          xpath: "//ImportExportXml/SolutionManifest/Version"

      - id: branch-name
        run: |
          echo "::set-output name=branchName::${{ env.solution }}_${{ steps.solution-version.outputs.info }}"

      - id: create-solution-branch
        uses: microsoft/powerplatform-actions/branch-solution@v0.1.8
        with:
          solution-folder: "Solutions/${{ env.solution }}"
          solution-target-folder: "Solutions/${{ env.solution }}"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          branch-name: ${{ steps.branch-name.outputs.branchName }}

      - uses: octokit/request-action@v2.x
        id: create_pr
        with:
          owner: "rajyraman"
          repo: ${{ github.repository }}
          route: POST /repos/:repo/pulls
          title: ${{ steps.branch-name.outputs.branchName }}
          head: ${{ steps.branch-name.outputs.branchName }}
          base: "main"
          maintainer_can_modify: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
